# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_grp_controller

  arm_grp_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - lift_joint
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6